version: "3.7"

services:
  api-server:
    container_name: bee-server
    image: nginx:1.19.3-alpine
    ports:
      - 8000:80
    volumes:
      - ./api/:/var/www
      - ./api/docker/nginx:/etc/nginx/conf.d/
    networks:
      - bee-network

  api:
    container_name: bee-api
    build:
      context: .
      dockerfile: ./api/docker/php/Dockerfile

    working_dir: /var/www/
    volumes:
      - ./api/:/var/www
    networks:
      - bee-network

  db:
    container_name: bee-db
    image: postgres:13.3-alpine
    ports:
      - 6432:5432
    environment:
      POSTGRES_DB: beedb
      POSTGRES_USER: beeuser
      POSTGRES_PASSWORD: beepass
      PGDATA: /data/postgres
    volumes:
      - bee-volume:/data/postgres
    networks:
      - bee-network

networks:
  bee-network:
    driver: bridge

volumes:
  bee-volume:
    driver: local
