version: "3.9"

services:
  api:
    container_name: bee-api
    build:
      context: ./api/docker/php
    volumes:
      - ./api/:/var/www/html
      - ./api/docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - 8000:80
    networks:
      - bee-network
    depends_on:
      - db

  app:
    container_name: bee-app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/app
    command: yarn start
    networks:
      - bee-network
    depends_on:
      - api

  db:
    container_name: bee-db
    image: postgres:13.3-alpine
    ports:
      - 6432:5432
    environment:
      POSTGRES_DB: beedb
      POSTGRES_USER: beeuser
      POSTGRES_PASSWORD: beepass
      PGDATA: /data/postgres
    volumes:
      - bee-volume:/data/postgres
    networks:
      - bee-network

networks:
  bee-network:
    driver: bridge

volumes:
  bee-volume:
    driver: local
