name: API

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "api"
          branch: master

      - name: Signing in on heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Running migrations
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku run -a ${{ secrets.HEROKU_APP_NAME }} php artisan migrate --force

      # - name: Creating the authorization code
      #   env:
      #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      #   run: |
      #     heroku run -a ${{ secrets.HEROKU_APP_NAME }} php artisan passport:keys --force
      #     heroku run -a ${{ secrets.HEROKU_APP_NAME }} php artisan passport:client --password --provider=users --name=beeOClient
