name: APP

on:
  pull_request:
    branches: [master]

jobs:
  app-pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ./app
        run: npm install

      - name: Build site
        working-directory: ./app
        run: npm run build

      - name: Deploy site to netlify
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: cd app && netlify link && netlify deploy --dir=build -p --open
